# Generated by Django 4.0.2 on 2022-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('country', models.CharField(max_length=40, verbose_name='Страна')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('dateReg', models.DateField(verbose_name='Дата рождения')),
                ('email', models.CharField(max_length=70, verbose_name='E-mail')),
            ],
        ),
    ]
